// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prism.Common.Database;

#nullable disable

namespace Prism.Common.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306065432_AddModelsFeature")]
    partial class AddModelsFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prism.Features.Models.Domain.InferenceInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GpuConfig")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastHealthError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("MaxContextLength")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTopLogprobs")
                        .HasColumnType("integer");

                    b.Property<string>("ModelId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("SupportsGuidedDecoding")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsLogprobs")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsMetrics")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsModelSwap")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsMultimodal")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTokenize")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("ProviderType");

                    b.HasIndex("Status");

                    b.ToTable("models_instances", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
