namespace Prism.Features.BatchInference.Domain;

/// <summary>
/// Represents a single inference result within a batch job.
/// </summary>
public sealed class BatchResult : BaseEntity
{
    /// <summary>
    /// Gets or sets the parent batch job ID.
    /// </summary>
    public Guid BatchJobId { get; set; }

    /// <summary>
    /// Gets or sets the source dataset record ID.
    /// </summary>
    public Guid RecordId { get; set; }

    /// <summary>
    /// Gets or sets the input text sent to the model.
    /// </summary>
    public string Input { get; set; } = "";

    /// <summary>
    /// Gets or sets the output text generated by the model.
    /// </summary>
    public string? Output { get; set; }

    /// <summary>
    /// Gets or sets the raw logprobs data as a JSON string.
    /// </summary>
    public string? LogprobsData { get; set; }

    /// <summary>
    /// Gets or sets the perplexity score.
    /// </summary>
    public double? Perplexity { get; set; }

    /// <summary>
    /// Gets or sets the number of tokens used for this inference.
    /// </summary>
    public int TokensUsed { get; set; }

    /// <summary>
    /// Gets or sets the inference latency in milliseconds.
    /// </summary>
    public long LatencyMs { get; set; }

    /// <summary>
    /// Gets or sets the processing status of this record.
    /// </summary>
    public BatchResultStatus Status { get; set; } = BatchResultStatus.Pending;

    /// <summary>
    /// Gets or sets the error message if processing failed.
    /// </summary>
    public string? Error { get; set; }

    /// <summary>
    /// Gets or sets the current retry attempt number.
    /// </summary>
    public int Attempt { get; set; }
}
