namespace Prism.Features.Playground.Domain;

/// <summary>
/// Defines the role of a message participant in a playground conversation.
/// </summary>
public enum MessageRole
{
    /// <summary>A system-level instruction message.</summary>
    System,

    /// <summary>A message from the user.</summary>
    User,

    /// <summary>A message generated by the assistant (model).</summary>
    Assistant
}
